baseURL:
languageCode: en-us
theme: PaperMod
title: Allen Hsieh

params:
  homeInfoParams:
    Title: "Hello Stranger"
    Content: Welcome to my blog
  socialIcons:
    - name: facebook
      url: https://www.facebook.com/yylunxie/
    - name: instagram
      url: https://www.instagram.com/yylunxie/
    - name: github
      url: https://www.github.com/yylunxie/
    - name: linkedin
      url: https://www.linkedin.com/in/yylunxie/
    - name: cv
      url: https://drive.google.com/file/d/12z31nVBcBgcXiNpt1833g8MRD3Ro4tfd/view?usp=sharing

  cover:
    linkFullImages: true

  ShowBreadCrumbs: true

  ShowReadingTime: true

  ShowShareButtons: true

  ShowPostNavLinks: true

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30
