baseURL: "https://yylunxie.me/"
languageCode: en-us
theme: PaperMod
paginate: 5
title: Allen Hsieh

defaultContentLanguage: en
defaultContentLanguageInSubdir: false

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-SCFTQCXK4Y
minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    contentDir: content/
    languageName: English
    languageCode: en
    weight: 1
    menu:
      main:
        - identifier: blogs
          name: Blogs
          url: /blogs/
          weight: 20
        - identifier: gallery
          name: Gallery
          url: /gallery/
          weight: 30
        - identifier: search
          name: Search
          url: /search/
          weight: 80
        - name: Tags
          url: tags/
          weight: 90
        - identifier: archives
          name: Archives
          url: /archives/
          weight: 99
  zh-tw:
    disabled: true
    contentDir: content/
    languageName: 中文
    languageCode: "zh-tw"
    weight: 2
    menu:
      main:
        - identifier: blogs
          name: 文章
          url: /blogs/
          weight: 20
        - identifier: gallery
          name: 相簿
          url: /gallery/
          weight: 30
        - identifier: search.zh-tw
          name: 搜尋
          url: /search/
          weight: 80
        - name: Tags
          url: tags/
          weight: 90
        - identifier: archives
          name: 典藏
          url: /archives/
          weight: 99

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: AllenHsieh
  description: "This is the website of Allen Hsieh"
  author: Allen Hsieh
  keywords: [Blog, Portfolio, Data Science, PaperMod]
  DateFormat: "January 2, 2006"
  assets:
    favicon: "images/open-book.png"
  ShareButtons: ["x", "linkedin", "facebook"]

  # profile-mode
  # profileMode:
  #   enabled: true # needs to be explicitly set
  #   title: "Welcome! \U0001F44B"
  #   subtitle: "This is the website of **Allen Hsieh**."
  #   imageUrl: "images/me.png"
  #   imageWidth: 120
  #   imageHeight: 120
  #   imageTitle: "Data Professor"
  #   buttons:
  #     - name: Blogs
  #       url: blogs
  #     # - name: Projects
  #     #   url: projects

  homeInfoParams:
    Title: "Welcome! \U0001F44B"
    Content: This is the website of **Allen Hsieh**.
      You can find my blogs and gallery here.

  socialIcons:
    # - name: facebook
    #   url: https://www.facebook.com/yylunxie/
    # - name: instagram
    #   url: https://www.instagram.com/yylunxie/
    - name: github
      url: https://www.github.com/yylunxie/
    - name: linkedin
      url: https://www.linkedin.com/in/yylunxie/
    # - name: cv
    #   url: https://drive.google.com/file/d/12z31nVBcBgcXiNpt1833g8MRD3Ro4tfd/view?usp=sharing

  cover:
    responsiveImages: false
    hidden: true # hide everywhere but not in structured data
    #   hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page

  # Other settings
  ShowReadingTime: false
  ShowShareButtons: true
  ShowCodeCopyButtons: true
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  disableScrollToTop: false
  disableAnchoredHeadings: true
  ShowToc: true # show table of content
  TocOpen: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  comments: true
  displayFullLangName: false

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

  label:
    text: "Allen Hsieh"
    icon: "images/open-book.png"
    iconHeight: 35

# Searching Function
outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search
