baseURL: "https://yylunxie.github.io/myblog/"
languageCode: en-us
theme: PaperMod
# paginate: 5
title: Allen Hsieh

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

#googleAnalytics: UA-123-45
minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: AllenHsieh
  description: "This is the website of Allen Hsieh"
  keywords: [Blog, Portfolio, Data Science]
  author: Allen Hsieh
  # author: ["Me", "You"] # multiple authors
  #images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  # ShowReadingTime: true
  # ShowShareButtons: true
  # ShowPostNavLinks: true
  # ShowBreadCrumbs: true
  # ShowCodeCopyButtons: false
  # disableSpecial1stPost: false
  # disableScrollToTop: false
  # comments: false
  # hidemeta: false
  # hideSummary: false
  # showtoc: false
  # tocopen: false

  label:
    text: "Allen Hsieh"
    icon: "static/img/sea.jpg"
    iconHeight: 35

  # profile-mode
  # profileMode:
  #   enabled: true # needs to be explicitly set
  #   title: "Welcome! \U0001F44B"
  #   subtitle: "This is the website of **Allen Hsieh**."
  #   imageUrl: "images/me.png"
  #   imageWidth: 120
  #   imageHeight: 120
  #   imageTitle: "Data Professor"
  #   buttons:
  #     - name: Blogs
  #       url: blogs
  #     # - name: Projects
  #     #   url: projects

  homeInfoParams:
    Title: "Welcome! \U0001F44B"
    Content: This is the website of **Allen Hsieh**. 
     You can find my blogs and gallery here.

  socialIcons:
    - name: facebook
      url: https://www.facebook.com/yylunxie/
    # - name: instagram
    #   url: https://www.instagram.com/yylunxie/
    - name: github
      url: https://www.github.com/yylunxie/
    - name: linkedin
      url: https://www.linkedin.com/in/yylunxie/
    # - name: cv
    #   url: https://drive.google.com/file/d/12z31nVBcBgcXiNpt1833g8MRD3Ro4tfd/view?usp=sharing

  cover:
    linkFullImages: true

  ShowBreadCrumbs: true

  ShowReadingTime: true

  ShowShareButtons: true

  ShowPostNavLinks: true

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"
  #   bing:
  #     SiteVerificationTag: "XYZabc"
  #   yandex:
  #     SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]


menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 40
    - identifier: blogs
      name: Blogs
      url: /blogs/
      weight: 20
    # - identifier: projects
    #   name: Projects
    #   url: /projects/
    #   weight: 3
    - identifier: gallery
      name: Gallery
      url: /gallery/
      weight: 30
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 99
